// Brand marks used inline across pages (extracted verbatim from the design files).
// Auto-generated by the migration converter; names assigned by dominant fill color.
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };

export function ArrowRightGlyph({ size = 22, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#C2571E"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M5 12h14"></path>
      <path d="m13 6 6 6-6 6"></path>
    </svg>
  );
}

export function GoogleG({ size = 22, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 48 48" aria-hidden="true" {...props}>
      <path
        fill="#4285F4"
        d="M45.12 24.5c0-1.56-.14-3.06-.4-4.5H24v8.51h11.84c-.51 2.75-2.06 5.08-4.39 6.64v5.52h7.11c4.16-3.83 6.56-9.47 6.56-16.17z"
      ></path>
      <path
        fill="#34A853"
        d="M24 46c5.94 0 10.92-1.97 14.56-5.33l-7.11-5.52c-1.97 1.32-4.49 2.1-7.45 2.1-5.73 0-10.58-3.87-12.31-9.07H4.34v5.7C7.96 41.07 15.4 46 24 46z"
      ></path>
      <path
        fill="#FBBC05"
        d="M11.69 28.18C11.25 26.86 11 25.45 11 24s.25-2.86.69-4.18v-5.7H4.34C2.85 17.09 2 20.45 2 24s.85 6.91 2.34 9.88l7.35-5.7z"
      ></path>
      <path
        fill="#EA4335"
        d="M24 10.75c3.23 0 6.13 1.11 8.41 3.29l6.31-6.31C34.91 4.18 29.93 2 24 2 15.4 2 7.96 6.93 4.34 14.12l7.35 5.7c1.73-5.2 6.58-9.07 12.31-9.07z"
      ></path>
    </svg>
  );
}

export function ShieldGlyph({ size = 21, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#8A837B"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M12 3l7.5 3v5.5c0 4.4-3.1 8.2-7.5 9.5-4.4-1.3-7.5-5.1-7.5-9.5V6z"></path>
    </svg>
  );
}

export function AmazonSmile({ size = 21, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={typeof size === "number" ? (size * 7) / 21 : size}
      viewBox="0 0 20 6"
      fill="none"
      aria-hidden="true"
      {...props}
    >
      <path d="M1.2 1.4c5 3 11.4 3.2 16.2.6" stroke="#FF9900" strokeWidth="1.7" strokeLinecap="round"></path>
      <path d="M15.4 3.5l3.2-2-1.1 3.6z" fill="#FF9900"></path>
    </svg>
  );
}

export function CircleCheckGlyph({ size = 22, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#2E9E4F"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="10"></circle>
      <path d="m8.5 12 2.5 2.5 5-5"></path>
    </svg>
  );
}

export function MetaLogo({ size = 22, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 -3 24 24" aria-hidden="true" {...props}>
      <path
        fill="#0866FF"
        d="M6.915 4.03c-1.968 0-3.683 1.28-4.871 3.113C.704 9.208 0 11.883 0 14.449c0 .706.07 1.369.21 1.973a6.624 6.624 0 0 0 .265.86 5.297 5.297 0 0 0 .371.761c.696 1.159 1.818 1.927 3.593 1.927 1.497 0 2.633-.671 3.965-2.444.76-1.012 1.144-1.626 2.663-4.32l.756-1.339.186-.325c.061.1.121.196.183.3l2.152 3.595c.724 1.21 1.665 2.556 2.47 3.314 1.046.987 1.992 1.22 3.06 1.22 1.075 0 1.876-.355 2.455-.843a3.743 3.743 0 0 0 .81-.973c.542-.939.861-2.127.861-3.745 0-2.72-.681-5.357-2.084-7.45-1.282-1.912-2.957-2.93-4.716-2.93-1.047 0-2.088.467-3.053 1.308-.652.57-1.257 1.29-1.82 2.05-.69-.875-1.335-1.547-1.958-2.056-1.182-.966-2.315-1.303-3.454-1.303zm10.16 2.053c1.147 0 2.188.758 2.992 1.999 1.132 1.748 1.647 4.195 1.647 6.4 0 1.548-.368 2.9-1.839 2.9-.58 0-1.027-.23-1.664-1.004-.496-.601-1.343-1.878-2.832-4.358l-.617-1.028a44.908 44.908 0 0 0-1.255-1.98c.07-.109.141-.224.211-.327 1.12-1.667 2.118-2.602 3.358-2.602zm-10.201.553c1.265 0 2.058.791 2.675 1.446.307.327.737.871 1.234 1.579l-1.02 1.566c-.757 1.163-1.882 3.017-2.837 4.338-1.191 1.649-1.81 1.817-2.486 1.817-.524 0-1.038-.237-1.383-.794-.263-.426-.464-1.13-.464-2.046 0-2.221.63-4.535 1.66-6.088.454-.687.964-1.226 1.526-1.548.5-.187.881-.27 1.095-.27z"
      ></path>
    </svg>
  );
}

export function ChevronRightGlyph({ size = 18, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A8A29A"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="m9 6 6 6-6 6"></path>
    </svg>
  );
}

export function WalmartSpark({ size = 22, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <g stroke="#FFC220" strokeWidth="3.4" strokeLinecap="round">
        <path d="M12 3.4v5.2"></path>
        <path d="M12 15.4v5.2"></path>
        <path d="M14.9 10.3l4.5-2.6"></path>
        <path d="M4.6 16.3l4.5-2.6"></path>
        <path d="M14.9 13.7l4.5 2.6"></path>
        <path d="M4.6 7.7l4.5 2.6"></path>
      </g>
    </svg>
  );
}

export function PinterestP({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <circle cx="12" cy="12" r="10" fill="#E60023"></circle>
      <path
        fill="#fff"
        d="M12.3 6.2c-3 0-4.9 1.9-4.9 4.3 0 1.1.6 2.4 1.6 2.8.2.1.3 0 .3-.1l.2-.8c0-.1 0-.2-.1-.3-.3-.4-.5-.9-.5-1.5 0-1.9 1.4-3.4 3.4-3.4 1.9 0 2.9 1.1 2.9 2.6 0 1.9-.9 3.5-2.2 3.5-.7 0-1.2-.6-1-1.3l.5-2c.1-.5-.2-.9-.7-.9-.7 0-1.3.7-1.3 1.7 0 .6.2 1 .2 1l-.9 3.6c-.2.9.1 2.2.1 2.3l1.1.5c.1 0 .1 0 .2-.1.1-.2.5-1.7.6-2.2 0 0 .4.7 1.5.7 2 0 3.5-1.9 3.5-4.4 0-2.3-2-4-4.5-4z"
      ></path>
    </svg>
  );
}

export function FileTextGlyph({ size = 30, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#171514"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"></path>
      <path d="M14 2v4a2 2 0 0 0 2 2h4"></path>
      <path d="M10 9H8"></path>
      <path d="M16 13H8"></path>
      <path d="M16 17H8"></path>
    </svg>
  );
}

export function Glyph1({ size = 20, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="#2E9E4F" aria-hidden="true" {...props}>
      <circle cx="12" cy="12" r="12"></circle>
      <path
        d="M17 8.5 10.5 15 7 11.5"
        stroke="#fff"
        strokeWidth="2.2"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}

export function Glyph2({ size = 21, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <g>
        <path
          fill="#18181B"
          d="M16.6 5.8A4.28 4.28 0 0 1 15.54 3h-3.09v12.4a2.59 2.59 0 0 1-2.59 2.5 2.6 2.6 0 0 1-2.6-2.6c0-1.72 1.66-3.01 3.37-2.48V9.66c-3.45-.46-6.47 2.22-6.47 5.64 0 3.33 2.76 5.7 5.69 5.7 3.14 0 5.69-2.55 5.69-5.7V9.01a7.35 7.35 0 0 0 4.3 1.38V7.3s-1.88.09-3.24-1.5z"
        ></path>
      </g>
    </svg>
  );
}

export function CircleCheckGlyph2({ size = 19, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#4E7A57"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="9.5"></circle>
      <path d="M8 12.2l2.7 2.7L16 9.6"></path>
    </svg>
  );
}

export function FileTextGlyph2({ size = 18, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#0071DC"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"></path>
      <path d="M14 2v4a2 2 0 0 0 2 2h4"></path>
      <path d="M10 9H8M16 13H8M16 17H8"></path>
    </svg>
  );
}

export function ShieldGlyph2({ size = 15, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#8A857F"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
    </svg>
  );
}

export function ShopifyBag({ size = 18, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <path
        fill="#95BF47"
        d="M16.1 4.7c0-.1-.1-.2-.2-.2l-1.8-.1-1.3-1.3c-.1-.1-.3-.1-.4-.1l-.6.2c-.3-.8-.8-1.5-1.6-1.5h-.1c-.2-.3-.6-.4-.9-.4-2.2.1-3.2 2.8-3.6 4.2l-1.5.5c-.5.1-.5.2-.5.6L2.4 20.3l9.1 1.7 5-1.1-.4-16.2zM9.7 3.5v.4L7.6 4.5c.4-1.3 1-2 1.6-2.2.2.3.4.7.5 1.2zM8.8 1.5c.2 0 .3 0 .4.2-.8.4-1.7 1.3-2.1 3.2L5.5 5.4c.4-1.2 1.3-3.8 3.3-3.9zm1.3 9.2s-.7-.4-1.5-.4c-1.2 0-1.3.8-1.3.9 0 1.1 2.8 1.2 2.8 3.6 0 1.9-1.2 3.1-2.9 3.1-2 0-2.9-1.2-2.9-1.2l.5-1.7s1 .9 1.9.9c.5 0 .7-.4.7-.7 0-1.3-2.3-1.4-2.3-3.7 0-1.8 1.3-3.6 4-3.6 1 0 1.6.3 1.6.3l-.6 2.5z"
      ></path>
      <path
        fill="#5E8E3E"
        d="M15.9 4.5l-1.8-.1-1.3-1.3c-.1-.1-.2-.1-.3-.1L11.9 22l5-1.1-.8-16.1c0-.2-.1-.3-.2-.3z"
      ></path>
    </svg>
  );
}

export function LockGlyph({ size = 13, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#8A857F"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <rect x="3" y="11" width="18" height="11" rx="2"></rect>
      <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
    </svg>
  );
}

export function TriangleAlertGlyph({ size = 16, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#D98B2B"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z"></path>
      <path d="M12 9v4"></path>
      <path d="M12 17h.01"></path>
    </svg>
  );
}

export function SearchGlyph({ size = 14, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A1A1AA"
      strokeWidth="1.8"
      strokeLinecap="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="11" cy="11" r="7"></circle>
      <path d="m21 21-4.3-4.3"></path>
    </svg>
  );
}

export function ShopifyBag2({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <path
        fill="#95BF47"
        d="M15.3 3.6c-.1 0-.3.1-.5.1l-.4-.9c-.3-.6-.8-.9-1.4-.9h-.1c-.1-.1-.2-.2-.3-.2-.6-.5-1.5-.4-2.2.2C9.8 2.4 9.4 3.3 9.2 4l-1.7.5c-.5.2-.5.2-.6.7L5.4 19.4 16 21.4l4.6-1L18 5.4c0-.3-.2-.4-.4-.4l-1.2-.1-1.1-1.3zm-1.4.6-1 .3v-.2c0-.6-.1-1.1-.2-1.5.5.1.8.7 1.2 1.4zm-1.9.6-2.1.6c.2-.8.6-1.5 1-1.9.2-.2.4-.3.6-.4.4.5.5 1.1.5 1.7zm-1-2.6c.2 0 .3 0 .4.1-.2.1-.4.3-.6.5-.6.6-1 1.6-1.2 2.5l-1.7.5c.5-1.6 1.6-3.5 3.1-3.6z"
      ></path>
      <path fill="#5E8E3E" d="M17.6 5 16.4 5l-1.1-1.3c-.1 0-.2.1-.4.1L16 21.4l4.6-1L18 5.4c0-.3-.2-.4-.4-.4z"></path>
      <path
        fill="#fff"
        d="M13 9.1l-.6 2s-.6-.3-1.4-.3c-1.1 0-1.2.7-1.2.9 0 1 2.6 1.4 2.6 3.7 0 1.8-1.2 3-2.7 3-1.9 0-2.8-1.2-2.8-1.2l.5-1.7s1 .9 1.8.9c.5 0 .8-.4.8-.7 0-1.3-2.1-1.4-2.1-3.5 0-1.8 1.3-3.5 3.8-3.5 1 0 1.3.4 1.3.4z"
      ></path>
    </svg>
  );
}

export function GoogleAnalyticsBars({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <rect x="3" y="13" width="4.4" height="8" rx="1.6" fill="#F9AB00"></rect>
      <rect x="9.8" y="8" width="4.4" height="13" rx="1.6" fill="#E37400"></rect>
      <rect x="16.6" y="3" width="4.4" height="18" rx="1.6" fill="#F9AB00"></rect>
    </svg>
  );
}

export function MicrosoftLogo({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <rect x="2.5" y="2.5" width="8.4" height="8.4" fill="#F25022"></rect>
      <rect x="13.1" y="2.5" width="8.4" height="8.4" fill="#7FBA00"></rect>
      <rect x="2.5" y="13.1" width="8.4" height="8.4" fill="#00A4EF"></rect>
      <rect x="13.1" y="13.1" width="8.4" height="8.4" fill="#FFB900"></rect>
    </svg>
  );
}

export function GoogleG2({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <rect x="9.2" y="2.6" width="5.6" height="16.4" rx="2.8" fill="#FBBC04" transform="rotate(24 12 5.6)"></rect>
      <rect x="9.2" y="2.6" width="5.6" height="16.4" rx="2.8" fill="#4285F4" transform="rotate(-24 12 5.6)"></rect>
      <circle cx="6.7" cy="17.9" r="3.5" fill="#34A853"></circle>
    </svg>
  );
}

export function SnapchatGhost({ size = 19, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <rect x="2" y="2" width="20" height="20" rx="5" fill="#FFFC00"></rect>
      <path
        fill="#171514"
        transform="translate(12 12) scale(.78) translate(-12 -12)"
        d="M12 3.6c2.4 0 4 1.8 4 4.2 0 .8-.1 1.5-.1 2 .4.1.9.1 1.3 0 .4-.1.8.1.8.5 0 .5-.6.9-1.3 1.1-.5.2-.8.3-.8.5.1.8 1.9 2.8 3.3 3.2.4.1.5.5.3.8-.5.5-1.7.8-2.3.9-.3 0-.4.3-.4.5-.1.4-.1.6-.5.6s-1.2-.3-1.9-.3c-1 0-1.5.9-2.8.9h-.2c-1.3 0-1.8-.9-2.8-.9-.7 0-1.5.3-1.9.3s-.4-.2-.5-.6c0-.2-.1-.5-.4-.5-.6-.1-1.8-.4-2.3-.9-.2-.3-.1-.7.3-.8 1.4-.4 3.2-2.4 3.3-3.2 0-.2-.3-.3-.8-.5-.7-.2-1.3-.6-1.3-1.1 0-.4.4-.6.8-.5.4.1.9.1 1.3 0 0-.5-.1-1.2-.1-2 0-2.4 1.6-4.2 4-4.2z"
      ></path>
    </svg>
  );
}

export function PauseGlyph({ size = 14, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A8A29A"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <rect x="14" y="4" width="4" height="16" rx="1"></rect>
      <rect x="6" y="4" width="4" height="16" rx="1"></rect>
    </svg>
  );
}

export function MessageCircleGlyph({ size = 18, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#3F3F46"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"></path>
    </svg>
  );
}

export function UserGlyph({ size = 16, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#171514"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="8" r="4"></circle>
      <path d="M20 21a8 8 0 0 0-16 0"></path>
    </svg>
  );
}

export function CheckGlyph({ size = 16, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#fff"
      strokeWidth="2.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="m5 12 5 5 9-10"></path>
    </svg>
  );
}

export function GridGlyph({ size = 12, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#C9C7C3"
      strokeWidth="1.6"
      aria-hidden="true"
      {...props}
    >
      <rect x="3" y="3" width="7" height="7"></rect>
      <rect x="14" y="3" width="7" height="7"></rect>
      <rect x="3" y="14" width="7" height="7"></rect>
      <rect x="14" y="14" width="7" height="7"></rect>
    </svg>
  );
}

export function WindowGlyph({ size = 12, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A9A7A2"
      strokeWidth="1.6"
      aria-hidden="true"
      {...props}
    >
      <path d="M4 4h16v16H4z"></path>
      <path d="M4 9h16"></path>
    </svg>
  );
}

export function SparkleGlyph({ size = 12, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A9A7A2"
      strokeWidth="1.6"
      aria-hidden="true"
      {...props}
    >
      <path d="M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"></path>
    </svg>
  );
}

export function ChartLineGlyph({ size = 12, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A9A7A2"
      strokeWidth="1.6"
      aria-hidden="true"
      {...props}
    >
      <path d="M3 3v18h18"></path>
      <path d="m7 15 4-4 3 3 5-6"></path>
    </svg>
  );
}

export function BellGlyph({ size = 14, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#52525B"
      strokeWidth="1.6"
      aria-hidden="true"
      {...props}
    >
      <path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"></path>
      <path d="M13.7 21a2 2 0 0 1-3.4 0"></path>
    </svg>
  );
}

export function TargetGlyph({ size = 21, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#E2703A"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="7"></circle>
      <circle cx="12" cy="12" r="2.4"></circle>
      <path d="M12 2v3M12 19v3M2 12h3M19 12h3"></path>
    </svg>
  );
}

export function CircleCheckGlyph3({ size = 15, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#5C5853"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="9"></circle>
      <path d="m8.5 12 2.5 2.5 4.5-5"></path>
    </svg>
  );
}

export function InfoGlyph({ size = 16, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#A8A29A"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="9"></circle>
      <path d="M12 11v5"></path>
      <path d="M12 8h.01"></path>
    </svg>
  );
}

export function EyeGlyph({ size = 15, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#6B655E"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7-10-7-10-7z"></path>
      <circle cx="12" cy="12" r="3"></circle>
    </svg>
  );
}

export function CirclePlusGlyph({ size = 12, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.9"
      strokeLinecap="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="8.5"></circle>
      <path d="M12 8v8"></path>
      <path d="M8 12h8"></path>
    </svg>
  );
}

export function CircleCheckGlyph4({ size = 18, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#5DBB7A"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="10"></circle>
      <path d="m9 12 2 2 4-4"></path>
    </svg>
  );
}

export function SearchGlyph2({ size = 24, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#171514"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="11" cy="11" r="8"></circle>
      <path d="m21 21-4.3-4.3"></path>
    </svg>
  );
}

export function ScanGlyph({ size = 20, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#5F5B55"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M3 7V5a2 2 0 0 1 2-2h2M17 3h2a2 2 0 0 1 2 2v2M21 17v2a2 2 0 0 1-2 2h-2M7 21H5a2 2 0 0 1-2-2v-2"></path>
      <circle cx="12" cy="12" r="3"></circle>
    </svg>
  );
}

export function Glyph3({ size = 14, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="#2E9E4F" aria-hidden="true" {...props}>
      <circle cx="12" cy="12" r="12"></circle>
      <path
        d="M17 8.5 10.5 15 7 11.5"
        stroke="#fff"
        strokeWidth="2.4"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}

export function ShoppingBagGlyph({ size = 20, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#171514"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"></path>
      <path d="M3 6h18"></path>
      <path d="M16 10a4 4 0 0 1-8 0"></path>
    </svg>
  );
}

export function MetaLogo2({ size = 44, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" {...props}>
      <circle cx="12" cy="12" r="12" fill="#0866FF"></circle>
      <path
        fill="#fff"
        d="M13.3 24v-9.3h3.1l.5-3.6h-3.6V8.8c0-1 .3-1.8 1.8-1.8H17V3.8c-.3 0-1.5-.1-2.8-.1-2.8 0-4.6 1.7-4.6 4.8v2.6H6.5v3.6h3.1V24z"
      ></path>
    </svg>
  );
}

export function RedoGlyph({ size = 18, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#3F3F46"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M15 5l6 6-6 6"></path>
      <path d="M21 11H11a7 7 0 0 0-7 7v1"></path>
    </svg>
  );
}

export function HeartGlyph({ size = 24, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#171514"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"></path>
    </svg>
  );
}

export function EyeOffGlyph({ size = 14, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#8A857F"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"></path>
      <path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"></path>
      <path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"></path>
      <path d="m2 2 20 20"></path>
    </svg>
  );
}

export function ClockGlyph({ size = 17, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="#8A857F"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="10"></circle>
      <polyline points="12 6 12 12 16 14"></polyline>
    </svg>
  );
}
