/** Every public route (README site map). Used by sitemap.ts and the QA screenshot run. */
export const SITE_ROUTES = [
  "/",
  "/platform/feed-management",
  "/platform/diagnostics",
  "/platform/rules-engine",
  "/platform/price-intelligence",
  "/platform/conversion-intelligence",
  "/channels",
  "/channels/google-shopping",
  "/channels/google-ads",
  "/channels/meta",
  "/channels/tiktok",
  "/channels/pinterest",
  "/channels/snapchat",
  "/channels/bing",
  "/channels/amazon",
  "/channels/walmart",
  "/channels/ebay",
  "/pricing",
  "/demo",
  "/contact",
  "/help",
  "/security",
  "/legal/privacy",
  "/legal/terms",
  "/legal/gdpr",
  "/legal/cookies",
] as const;
